// client/pages/auth/signup.tsx
import React from 'react';

const signup = () => {
  return (
    <div>
      <form>
        <div>
          <label>email</label>
          <input type="text" />
        </div>
        <div>
          <label>ユーザーネーム</label>
          <input type="text" />
        </div>
        <div>
          <label>パスワード</label>
          <input type="password" />
        </div>
        <button>始める</button>
      </form>
    </div>
  );
};

export default signup;

// client/src/pages/signup.svelte
<script lang="ts">
  console.log('This is a signup page!');
</script>

<h1>This is signup page!</h1>
<h2>Please enter your info!</h2>

<form action="">
  <div>
    <label for="">email</label>
    <input type="email" placeholder="email" />
  </div>
  <div>
    <label for="">username</label>
    <input type="text" placeholder="username" />
  </div>
  <div>
    <label for="">password</label>
    <input type="password" placeholder="password" />
  </div>
  <input type="submit" />
</form>
