// client/src/pages/login.svelte
<script lang="ts">
  console.log('this is a login page!');
</script>

<h1>This is a login page!</h1>
<h2>please enter email and password!</h2>
<form action="">
  <div>
    <label for="">email or username</label>
    <input type="text" placeholder="email of username" />
  </div>
  <div>
    <label for="">password</label>
    <input type="password" placeholder="password" />
  </div>
  <input type="submit" />
</form>

// client/pages/auth/login.tsx
import React from 'react';

const login = () => {
  return (
    <div>
      <form>
        <div>
          <label>ユーザーネーム</label>
          <input type="text" />
        </div>
        <div>
          <label>パスワード</label>
          <input type="password" />
        </div>
        <button>ログイン</button>
      </form>
    </div>
  );
};

export default login;
